### ISSUE TITLE
Issue understanding the logic of the program

### ISSUE THREAD

**Issue by jeiros** [drroe/CreateRemdDirs#4]
Sorry if I'm missing something obvious, 

I want to test this software but I'm having problems creating the input directories. I want to do Parallel Tempering, and have generated the temperature list with an automatic [generator](http://folding.bmc.uu.se/remd/). I have stored the temperatures in the `Temperature.dat` file, containing in total 263 temperatures.

My `remd.opts` is set up like so:

```
DIMENSION   Temperatures.dat
NSTLIM      500
NUMEXCHG    100
TOPOLOGY    /Users/je714/test_createRMDdirs/top.prmtop
CRD_FILE    /Users/je714/test_createRMDdirs
MDIN_FILE   pme.remd.in
FULLARCHIVE 0
```

_I've tried changing the_ `CRD_FILE` _variable from_ `/Users/je714/test_createRMDdirs` _with_ `/Users/je714/test_createRMDdirs/inpu_coords.inpcrd` _but it makes no difference_.

And my `pme.remd.in` file is the following:

```
  ntwx = 5000
 ioutfm = 1,
 ntwr = 100000,
 ntxo = 2,
 ntpr = 5000,
 iwrap = 1,
 ntc = 2,
 ntf = 2,
 cut = 8.0,
 ntt = 3,
 gamma_ln = 1,
 dt = 0.004,
 ig = -1,
 ntb=2,
 ntp=1,
 barostat=2,
```

Now I use CreateRemdDirs to setup 10 runs but I get the following error:

```
$ CreateRemdDirs -b 0 -e 10

CreateRemdDir: Amber run input creation/job submission/job check.
Version: 0.9b
Daniel R. Roe, 2015
  START            : 0
  STOP             : 10
Working Dir: /Users/je714/test_createRMDdirs
Reading input from file: remd.opts
    Dim 1: Temperature exchange from 300 K to 500.48 K (263)
  MDIN_FILE        : pme.remd.in
  NSTLIM=500, DT=-1.000000
  NUMEXCHG=100
  CRD_DIR          : /Users/je714/test_createRMDdirs/inputcrd.inpcrd
  1 dimensions, 263 total replicas.
Creating 11 runs from 0 to 10
  RUNDIR: run.000
    Run 0: irest=0, ntx=1
Error: Coords /Users/je714/test_createRMDdirs/inputcrd.inpcrd/001.rst7 not found.
```

It does create a `run.000` directory with the following content though:

```
$ tree run.000/
run.000/
├── [ 102]  INPUT
│   └── [ 367]  in.001
└── [   0]  groupfile

1 directory, 2 files
```

What am I doing wrong? Why haven't the other directories been created? 

I've asked here rather than in the AMBER mailing list as it seems this is still in development and there's no info about this software in the manual.

**Comment by drroe** [comment]
First, I had no idea people were using this, so thanks for the feedback!

> containing in total 263 temperatures.

Quick note - I don't think Amber will let you have an odd number of replicas. Easiest way to fix this is to get rid of one of your temperatures (the top- or bottom-most one).

> Error: Coords /Users/je714/test_createRMDdirs/inputcrd.inpcrd/001.rst7 not found.

Just to double check, are you certain the `remd.opts` file you posted is the one you used? The one you posted has
```
CRD_FILE    /Users/je714/test_createRMDdirs
```
but the output says
```
CRD_DIR          : /Users/je714/test_createRMDdirs/inputcrd.inpcrd
```
Also, I hardly ever use CRD_DIR (since it locks me into one directory). I just use the `-c` command line option on the first run. Maybe try that out?

If the directory is set correctly, are there Amber coordinate (i.e. "restart") files there? The program currently expects the files to have the format `XXX.rst7` where XXX is a three digit number corresponding to the replica. So for 262 replicas the program will expect 001.rst7 through 262.rst7 to be present in your input coordinates directory.

Thanks again for trying it out!

**Comment by jeiros** [comment]
No worries! I think this program can save me a lot of time so that's why I'm testing it out :thumbsup:
So, from the command line, the -c flag has the directory where the `inpcrd` file is, got it. 

But here's where I'm failing to understand the logic (I' m probably confused on how REMD works). Why would I have 262 different restart files? Are they identical?

I thought that I could get the different systems at each tempertaure just from a topology and inpcrd pair of files.

Thanks for answering so quickly!

**Comment by drroe** [comment]
> I thought that I could get the different systems at each tempertaure just from a topology and inpcrd pair of files.

You can do that, but you may not always want to do that (e.g. if you are restarting from a previous run). If you want to use a single file you can get around it will soft links, e.g.
```sh
#!/bin/bash
FILE=myrestart.rst7
for (( i=1; i <= 262; i++)) ; do
  ln -s $FILE `printf "%03i.rst7" $i`
done
```
Adding an option to start from a single set of coordinates is a good idea though. I'll create an issue for it.

**Comment by jeiros** [comment]
Thanks! Got it working now :)
Now onto figuring out how I can set this up with GPUs, but that's another story...

**Comment by drroe** [comment]
Seems safe to close this now :-)
